[project]
name = "htpk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "litestar>=2.18.0",
    "python-multipart>=0.0.20",
    "sniffio>=1.3.1",
    "uvicorn>=0.38.0",
]
